#!/bin/bash
# ==============================================================================
# PPDM Generic Application Agent - RHEL Bare Metal Recovery (ReaR) Backup Script
# ==============================================================================
# Description : Creates a ReaR bootable ISO and system backup, storing output
#               to the PPDM-managed BoostFS target directory.
# Requirements: - ReaR (relax-and-recover) installed on the target host
#               - FUSE installed (required for BoostFS)
#               - PPDM Generic Application Agent (PaaS type) configured
#               - Run as root
# Tested PPDM : 19.22
# Author      : <your@dell.com>
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# PPDM Environment Variables (injected by PPDM agent)
# ------------------------------------------------------------------------------
# DD_TARGET_ASSET_BASE_PATH : BoostFS mount point managed by PPDM
# BACKUP_LEVEL              : FULL (incremental not supported for BMR)
# ASSET_USERNAME            : Asset credentials (if required)
# ASSET_PASSWORD            : Asset credentials (if required)
#
# Note: Application Type must be set to "PaaS" in PPDM asset configuration.
# ------------------------------------------------------------------------------

REAR_CONFIG_DIR="/etc/rear"
REAR_SITE_CONF="${REAR_CONFIG_DIR}/site.conf"
REAR_SITE_CONF_BACKUP="${REAR_CONFIG_DIR}/site.conf.ppdm_backup"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOGFILE="/var/log/ppdm_rear_backup_${TIMESTAMP}.log"

# ==============================================================================
# Functions
# ==============================================================================

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOGFILE}"
}

error_exit() {
    log "ERROR: $*"
    restore_rear_config
    exit 1
}

check_prerequisites() {
    log "Checking prerequisites..."

    # Root check
    [[ $EUID -eq 0 ]] || error_exit "This script must be run as root."

    # ReaR installed
    command -v rear &>/dev/null || error_exit "ReaR is not installed. Install with: dnf install rear"

    # PPDM target path
    [[ -n "${DD_TARGET_ASSET_BASE_PATH:-}" ]] || \
        error_exit "DD_TARGET_ASSET_BASE_PATH is not set. Ensure PPDM agent is configured correctly."

    # Target path accessible
    [[ -d "${DD_TARGET_ASSET_BASE_PATH}" ]] || \
        error_exit "Target path '${DD_TARGET_ASSET_BASE_PATH}' does not exist or is not mounted."

    # BACKUP_LEVEL check (BMR only supports FULL)
    if [[ "${BACKUP_LEVEL:-FULL}" != "FULL" ]]; then
        log "WARNING: BACKUP_LEVEL='${BACKUP_LEVEL}' is not supported for BMR. Proceeding as FULL."
    fi

    log "Prerequisites OK."
}

backup_rear_config() {
    if [[ -f "${REAR_SITE_CONF}" ]]; then
        log "Backing up existing ReaR site.conf..."
        cp "${REAR_SITE_CONF}" "${REAR_SITE_CONF_BACKUP}"
    fi
}

restore_rear_config() {
    if [[ -f "${REAR_SITE_CONF_BACKUP}" ]]; then
        log "Restoring original ReaR site.conf..."
        mv "${REAR_SITE_CONF_BACKUP}" "${REAR_SITE_CONF}"
    else
        # No original existed — remove the one we created
        [[ -f "${REAR_SITE_CONF}" ]] && rm -f "${REAR_SITE_CONF}"
    fi
}

configure_rear() {
    log "Configuring ReaR to target: ${DD_TARGET_ASSET_BASE_PATH}"

    mkdir -p "${REAR_CONFIG_DIR}"

    cat > "${REAR_SITE_CONF}" <<EOF
# Auto-generated by PPDM Generic Application Agent
# $(date)

OUTPUT=ISO
BACKUP=NETFS

# PPDM BoostFS mount point
BACKUP_URL="file://${DD_TARGET_ASSET_BASE_PATH}"
OUTPUT_URL="file://${DD_TARGET_ASSET_BASE_PATH}"

# Optional: exclude large/unnecessary paths from backup
EXCLUDE_BACKUP=( ${EXCLUDE_BACKUP:-} )

# Optional: set backup compression (default: gzip)
BACKUP_PROG_COMPRESS_OPTIONS=( --gzip )
BACKUP_PROG_COMPRESS_SUFFIX=".gz"
EOF

    log "ReaR site.conf written."
}

run_rear_backup() {
    log "Starting ReaR backup (rear mkbackup)..."
    rear -v mkbackup 2>&1 | tee -a "${LOGFILE}" || \
        error_exit "ReaR backup failed. Check ${LOGFILE} for details."
    log "ReaR backup completed successfully."
}

verify_output() {
    log "Verifying output files in ${DD_TARGET_ASSET_BASE_PATH}..."

    local hostname
    hostname=$(hostname -s)

    # ReaR typically writes: <hostname>.iso and backup.tar.gz
    local iso_file
    iso_file=$(find "${DD_TARGET_ASSET_BASE_PATH}" -name "${hostname}*.iso" -newer "${LOGFILE}" 2>/dev/null | head -1)

    local backup_file
    backup_file=$(find "${DD_TARGET_ASSET_BASE_PATH}" -name "backup.tar*" -newer "${LOGFILE}" 2>/dev/null | head -1)

    if [[ -z "${iso_file}" ]]; then
        log "WARNING: ISO file not found in target path. Verify ReaR output."
    else
        log "ISO  : ${iso_file} ($(du -sh "${iso_file}" | cut -f1))"
    fi

    if [[ -z "${backup_file}" ]]; then
        log "WARNING: Backup archive not found in target path."
    else
        log "Backup archive: ${backup_file} ($(du -sh "${backup_file}" | cut -f1))"
    fi
}

# ==============================================================================
# Main
# ==============================================================================

log "======================================================"
log " PPDM Generic App Agent - RHEL BMR (ReaR) Backup"
log " Host     : $(hostname)"
log " PPDM Target: ${DD_TARGET_ASSET_BASE_PATH:-NOT SET}"
log " Backup Level: ${BACKUP_LEVEL:-FULL}"
log "======================================================"

check_prerequisites
backup_rear_config
configure_rear
run_rear_backup
verify_output
restore_rear_config

log "Backup script completed. Log: ${LOGFILE}"
exit 0